name: eq2425-env # for project 1 and 2
channels:
  - conda-forge
dependencies:
  - python==3.7
  - ipykernel
  - matplotlib
  - pandas
  - scipy
  - pip
  - sklearn
  - pip:
      - opencv-contrib-python==3.4.2.16
      - tqdm
